/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static university2.connectdb.connect;

/**
 *
 * @author w
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    int choose;
    Connection con=null;
    PreparedStatement p=null;
    ResultSet res=null;
    
    public student() {
        initComponents();
        
        choose=mainmenu.ch;
        
        if(choose==2){
        this.setTitle("update student");
        add.setText("update");
        name.setEnabled(false);
        phone.setEnabled(false);
        male.setEnabled(false);
        female.setEnabled(false);
        
        }
         if(choose==3){
        this.setTitle("Delete student");
        add.setText("Delete");
        name.setEnabled(false);
        phone.setEnabled(false);
        male.setEnabled(false);
        female.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Student phone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 20));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        phone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, -1));

        number.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberKeyReleased(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Student name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/73f594dcf26826f1d6638da8dcb14924.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 10, 380, 270));

        setSize(new java.awt.Dimension(380, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         if(choose==1){
             try {
                 insert();
             } catch (SQLException ex) {
               System.out.println(ex.getMessage());
             }
         }
         else if(choose==2){
          update();
         }
         else{
          delete();
         }
    }//GEN-LAST:event_addActionPerformed

    private void numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyPressed
       if(evt.getKeyCode()==evt.VK_ENTER)
       {
         if(number.getText().equals("")){
         JOptionPane.showMessageDialog(null,"There are empty fields");
         }else{
           
             try {
                   con=connect();
                 p=con.prepareStatement("select * from student where id='"+Integer.parseInt(number.getText())+"'");
                 res=p.executeQuery();
                 
                 if(res.next()){
                      
                     
                    number.setEnabled(false);
                    
                    name.setText(res.getString(2));
                    name.setEnabled(true);
                    phone.setText(res.getString(4));
                    phone.setEnabled(true);
                    
                    String gender=res.getString(5);
                    if(gender.equals(female.getText())){
                       female.setSelected(true);
                    }else{
                       male.setSelected(true);
                    }
                      male.setEnabled(true);
                      female.setEnabled(true);
                 }else{
                JOptionPane.showMessageDialog(null, "رقم الطالب غير موجود");

                 }
             } catch (SQLException ex) {
                 System.out.println(ex.getMessage());
             }finally{
             
                 try {
                     con.close();
                      p.close();
                     res.close();
                 } catch (SQLException ex) {
                     Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
             }
             
         
         }
       
       
       }
    }//GEN-LAST:event_numberKeyPressed

    private void numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyReleased
    }//GEN-LAST:event_numberKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
      
    private void insert() throws SQLException {
        String gender=male.getText();
      if(female.isSelected()){
      
      gender=female.getText();
      }
        
      if(number.getText().equals("") || name.getText().equals("") ||phone.getText().equals("") ||
              male.isSelected() && female.isSelected()){
        JOptionPane.showMessageDialog(null, "There are empty fields");
      }
      else{
            con=connect();
            p=con.prepareStatement("select * from student where id='"+Integer.parseInt(number.getText())+"'");
            res=p.executeQuery();
            if(res.next()){
                     JOptionPane.showMessageDialog(null, "رقم الطالب موجود مسبقا");
            
            }else{
            
            
          con=connect();
          p = con.prepareStatement("insert into student values('"+Integer.parseInt(number.getText())+"','"+name.getText()+"','123','"+phone.getText()+"','"+gender+"','-1','0','0','0')");
            p.execute();
          JOptionPane.showMessageDialog(null,  " done");
          number.setText("");
          name.setText("");
          phone.setText("");
          male.isSelected();
          female.isSelected();

            
           
        }  
            }
          con.close();
                 p.close();
            res.close();
            
      
      }
    
   

    private void update() {
        String gender=male.getText();
      if(female.isSelected()){
      gender=female.getText();
      }
      if(name.getText().equals("") ||phone.getText().equals("") ||
              male.isSelected() && female.isSelected()){
        JOptionPane.showMessageDialog(null, "There are empty fields");
      }else{
            con=connect();
            try {
                p=con.prepareStatement("update student set name='"+name.getText()+"',phone='"+phone.getText()+"',gender='"+gender+"' where id='"+Integer.parseInt(number.getText())+"'");
                p.execute();
               JOptionPane.showMessageDialog(null, "done");
               
               number.setText("");
          name.setText("");
          phone.setText("");
          male.isSelected();
          female.isSelected();
          number.setEnabled(true);
          name.setEnabled(false);
          phone.setEnabled(false);
          male.setEnabled(false);
          female.setEnabled(false);


            } catch (SQLException ex) {
                Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
             
                 try {
                     con.close();
                      p.close();
                     res.close();
                 } catch (SQLException ex) {
                     Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
             }

      }
    }

    private void delete() {
             if(number.getText().equals("")){
              JOptionPane.showMessageDialog(null, "There are empty fields");

    }else{ 
                 
                
                 try {
                      con=connect();
                     p=con.prepareStatement("delete from student where id='"+Integer.parseInt(number.getText())+"' ");
                     p.execute();
                     JOptionPane.showMessageDialog(null, "done");
                     
            number.setText("");
          name.setText("");
          phone.setText("");
          male.isSelected();
          female.isSelected();
          number.setEnabled(true);
          name.setEnabled(false);
          phone.setEnabled(false);
          male.setEnabled(false);
          female.setEnabled(false);
                 } catch (SQLException ex) {
                     Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                 }finally{
             
                 try {
                     con.close();
                      p.close();
                     res.close();
                 } catch (SQLException ex) {
                     Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
             }
              

      }
}
}
